### ISSUE TITLE
Consider a Mechanism to Register Additional Beans with Dynamic Flow Registration

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-integration-java-dsl#125]
Currently, if a flow needs additional external beans, the client has to register/initialize them.

See https://github.com/spring-projects/spring-integration-samples/pull/178

Consider some kind of mechanism so that additional beans can be registered/initialized, something like...

    register("foo", myFlow, aMapOfSingletons);

or a callback of some kind.

**Comment by artembilan** [comment]
Well, I wonder if we can think more and return from the `IntegrationFlowContext.register()` something like `IntegrationFlowRegistration` with all useful support methods as a chain:
```
registration.addComponent(id, bean);
registration.getMessagingTemplate();
registration.getId();
registration.getInputChannel();
```
anything else?

Or even farther: return `IntegrationFlowRegistrationBuilder` with `id` and `autoStartup` options and, yes, `addComponent()`. 
Then the `.build()` (or `.get()`? In terms of our Java DSL) will return that `IntegrationFlowRegistration` with those post-registration options to use in the future.

Any other ideas/additions ?

**Comment by garyrussell** [comment]
Looks good; presumably `addComponent()` can check for `InitializingBean` and call `afterPropertiesSet()`.

BTW, although the DSL registers (and initializes) non-beans as beans, bf.initializeBean() only deals with the `...Aware` callbacks. Notice that I had to declare my router as a `@Bean` to get autowiring.

So, I wonder if we should not advertise that feature? Or at least explain the limitations.

**Comment by artembilan** [comment]
I have just overridden your code to the:
```
return f -> f.route(new TcpRouter());
```
and indeed `@Autowired` aren't populated.
That sounds sad, because even SI Core uses `bf.initializeBean()` feature, although we may never meet there `@Autowired` because everything is built-in.

But, eh, for Java DSL that is a good catch and nasty bug.

Even the  `bf.initializeBean()` calls `wrappedBean = applyBeanPostProcessorsBeforeInitialization(wrappedBean, beanName);`, looks like `AutowiredAnnotationBeanPostProcessor` does work already.

But I see that we can use it internally afterward:
```
AutowiredAnnotationBeanPostProcessor bpp = new AutowiredAnnotationBeanPostProcessor();
bpp.setBeanFactory(this.beanFactory);
bpp.processInjection(target);
```

**Comment by garyrussell** [comment]
cool
