### ISSUE TITLE
Arbitrary Component Registration Problem

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-integration-java-dsl#137]
When registering arbitrary components added to the component registration, the BPP uses logic to attempt to determine if the object is already registered as a bean and, if not, registers it.

BPP:

	Collection<?> values = this.beanFactory.getBeansOfType(component.getClass(), false, false).values();
	if (!values.contains(component)) {
        ...

This won't work (won't find the existing instance) if the arbitrary bean has been proxied by some other BPP.

I also have some concerns about calling `getBeansOfType()` from `postProcessBeforeInitialization()` - won't that cause early bean instantiation?

**Comment by artembilan** [comment]
>  if the arbitrary bean has been proxied by some other BPP.

Maybe you have some sample to play because we have such a test-case:
```
@Bean
@SecuredChannel(interceptor = "channelSecurityInterceptor", sendAccess = "ROLE_ADMIN")
public MessageChannel transformSecuredChannel() {
	return new DirectChannel();
}

@Bean
public IntegrationFlow httpInternalServiceFlow() {
	return IntegrationFlows
			.from(Http.inboundGateway("/service/internal")
					.requestMapping(r -> r.params("name"))
					.payloadExpression("#requestParams.name"))
			.channel(transformSecuredChannel())
			.<List<String>, String>transform(p -> p.get(0).toUpperCase())
			.get();
}
```
Indeed `transformSecuredChannel` is a Proxy, but `IntegrationFlowBeanPostProcessor` properly extract it from the `BF` and skips a bean declaration for that `.channel(transformSecuredChannel())` definition.

Regarding "early bean instantiation"...
Well, we have a problem in the `BeanFactoryPostProcessor` or when we use `allowEagerInit = true`. Everything rest works as usual and the same we have when we just use `@Autowired` everywhere.
See `AutowiredAnnotationBeanPostProcessor`.

If the issue had a place, we would be notified non one time already.

**Comment by garyrussell** [comment]
I think this is invalid - of course, Spring will guarantee that all BPPs will have run on the bean before it's injected into the flow so, I agree, if it's already proxied, it will be found.

**Comment by artembilan** [comment]
I understand what you say, but that still isn't clear to me what is invalid: our logic in the `BPP` or this issue?

If the last one, please, close it!

Otherwise let's continue discussion, but I need some materials to play.

Thanks

**Comment by garyrussell** [comment]
I was concurring that this (issue) is invalid 😄
