### ISSUE TITLE
Sample for xml-namespace

### ISSUE THREAD

**Issue by baudo2048** [spring-projects/spring-integration-java-dsl#14]
In order to convert xml-based configuration to java config using SI Java DSL, please provide a sample for this:

````xml
	<int:chain input-channel="inputChannel">
		<int-xml:xpath-filter match-value="my:namespace"
							  discard-channel="wrongMessagesChannel">
			<int-xml:xpath-expression expression="namespace-uri(/*)" />
		</int-xml:xpath-filter>
		<int-xml:xpath-router evaluate-as-string="true"
							  resolution-required="false"
							  default-output-channel="wrongMessagesChannel">
			<int-xml:xpath-expression expression="local-name(/*)" />
			<int-xml:mapping value="Tags" channel="splittingChannel" />
			<int-xml:mapping value="Tag" channel="receivedChannel" />
		</int-xml:xpath-router>
	</int:chain>
````

**Comment by artembilan** [comment]
@baudo2048 , provide, please an XML to test the case.
I'm going to show that as test within the project and it will be added to the PR #13 .

Even if it looks like StackOverflow question we can cover it with projects tests.

Thank you for the feedback!

**Comment by artembilan** [comment]
@baudo2048 , take a look, please https://github.com/artembilan/spring-integration-java-dsl/commit/fc3969668e55aef4ae4ef5a42b1520eb07af070d#diff-3fa5446ee1355d2122ff62358d734e3bR74.

I agree that it isn't so convenient from `fluent API perspective`, but at least it works, because we always can combine any raw Java configuration with DSL. And maybe that was a reason because we didn't do anything for XML adapters in the DSL :smile: 

Let us know if it appropriate for you and share you thoughts how it would look to make XML adapters more closer to DSL style.

**Comment by baudo2048** [comment]
@artembilan, thanks a lot, that is helpful for me and "xpathRouter()"-method give me an understanding on how to configure other xpath-specific endpoints (e.g. <xpath-splitter>).

From fluent API perspective maybe Filters and Routers builders with a set of out of the box concrete builders could help readability and easy to use. Please take this is only as an abstract idea. Thanks.

**Comment by artembilan** [comment]
Yes, I also thought about that. Fortunately we already have `Transformers`. The factory method can accept that router (selector) specific options, but generic ones can be provided from the `EndpointSpec`. That requires some other improvements to the flow definition methods, but it is just a routine.

Let me know and I close this issue as resolved and open new for those fluent API cases.

**Comment by baudo2048** [comment]
yes, my issue is solved.
