### ISSUE TITLE
Support for "order" attribute of handlers subscribing on publish-subscribe channel

### ISSUE THREAD

**Issue by chiknrice** [spring-projects/spring-integration-java-dsl#143]
The xml configuration provides the "order" attribute for subscribers of a publish-subscribe channel to establish the order of invocation of the subscribers.  I'm not sure if there's a way to do this in the DSL but if currently there's none, this is a request for that feature.

Thanks.

**Comment by artembilan** [comment]
You can do that via endpoint options:
```
.transform((Integer p) -> p * 2, e -> e.order(2))
```

**Comment by chiknrice** [comment]
Thanks a lot for that!  Very nice work you're doing here.

**Comment by xak2000** [comment]
### For the future googlers:

If you want, as me, to just order `IntegrationFlows` between each other where both integration flows started from single `publishSubscribe` channel, then you can use `.bridge(c -> c.order(2))` instead of `transform`.

For example:

```
	@Bean
	public MessageChannel dailyRegistryErrorChannel() {
		return MessageChannels.publishSubscribe().get();
	}

	@Bean
	public IntegrationFlow markDailyRegistryFileAsRejectedFlow() {
		return IntegrationFlows.from(dailyRegistryErrorChannel())
				.handle(m -> handleMessage(m))
				.get();
	}

	@Bean
	public IntegrationFlow dailyRegistryErrorLoggingFlow() {
		return IntegrationFlows.from(dailyRegistryErrorChannel())
				.bridge(c -> c.order(Ordered.HIGHEST_PRECEDENCE))
				.channel(errorChannel)
				.get();
	}
```

This way the `dailyRegistryErrorLoggingFlow` will be ordered before `markDailyRegistryFileAsRejectedFlow`.

You can also add `.bridge(c -> c.order(5))` at start of `markDailyRegistryFileAsRejectedFlow` to make it's subscribtion order explicit.

I tried to order my flows with `@Order` annotations on `IntegrationFlow` beans, but unfortunately it doesn't work.
