### ISSUE TITLE
Support XD style labels in integration flow

### ISSUE THREAD

**Issue by twicksell** [spring-projects/spring-integration-java-dsl#15]
It would be nice to support labels in the way Spring XD does to apply useful names to parts of the flow. That way when we look at the history header of a message we can see:

```
someFlow,someCustomLabel,AnotherLabel
```
instead of 

```
someFlow,someFlow.channel#0,someFlow.channel#1
```

It would probably be cleaner to read if all IntegrationFlowDefinition methods started with an option String label argument, but that might get a bit difficult to implement. Maybe an extra method on IntegrationFlowDefinition to provide an alias to the previous element?

```
IntegrationFlows.from("someFlow")
        .gateway("someChannel").as("someCustomLabel")
        .gateway("someOtherChannel").as("AnotherLabel")
        .get();
```

**Comment by artembilan** [comment]
@twicksell , thank you for the feedback, but it seems for me that we already provide such a feature in face of explicit `id` for endpoint or message channel:

```
.channel("someCustomLabel")
.handle((p, h) -> ..., e -> e.id("AnotherLabel"))
```

Doesn't that help you?
Don't see reason for extra option, if it is applied to the `MessageChannel` anyway, since we just can use an explicit `.channel()` definition.

**Comment by twicksell** [comment]
Ah, you're right. It hadn't occurred to me to use the EndpointSpec. User error, thanks Artem.
