### ISSUE TITLE
defaultOutputToParentFlow not documented

### ISSUE THREAD

**Issue by nucknorris** [spring-projects/spring-integration-java-dsl#153]
As announced in the [release blog post](https://spring.io/blog/2016/09/15/java-dsl-for-spring-integration-1-2-milestone-2-is-available) and in [this comment](https://stackoverflow.com/questions/43375049/spring-integration-and-dsl-upgrade-one-way-messagehandler-and-it-isnt-appro#comment73813437_43375480) the routing logic has been changed and `defaultOutputToParentFlow` has been added. It would be nice if this was documented in the wiki.

**Comment by nucknorris** [comment]
Adding to that, is there any (reliable) documentation of the Spring Integration Java DSL? The wiki doesn't even has information from [blogosts from mid-2016](https://spring.io/blog/2016/07/08/java-dsl-for-spring-integration-1-2-m1-and-1-1-3-are-available) (e.g. Operator log() is not documented).

**Comment by artembilan** [comment]
@nucknorris ,

Thank you for the feedback!
Well, we just don't have enough resources to cover everything.
Driven by the community to deliver as much features as possible we indeed may miss to document it.

I'll fix mentioned concerns here, but bear in mind that we are in process migrating this project fully to the Spring Integration one since version `5.0`. Therefore documentation will be addressed there as well: https://jira.spring.io/browse/INT-4277

Well, the contribution is welcome, of course. But I guess you don't have permissions to edit Wiki 😄

**Comment by nucknorris** [comment]
Thank you for adding the missing information. I can see how it's not easy to always find resources, for sure. Maybe a note on top of the wiki could at least inform the reader about the its state, and/or link to the relevant blog posts.

Sadly, as you already mentioned, the wiki doesn't support pull-requests or even a change history, so contributing is not really possible.

**Comment by artembilan** [comment]
I added the mentioned omissions into the Wiki.

Thank you for your feedback!
