### ISSUE TITLE
Include builder method in FTP for a Stream Inbound Channel Adapter

### ISSUE THREAD

**Issue by victor-ferrer** [spring-projects/spring-integration-java-dsl#154]
Hi,

I´m using a`FtpStreamingMessageSource` and I had a hard time instantiating it. I would like to propose a builder method in the `org.springframework.integration.dsl.ftp.FTP` class for that.

This is the code I had to write for my streaming message source:

```java
    @Bean
    public DefaultFtpSessionFactory ftpSessionFactory(){
        
        DefaultFtpSessionFactory toReturn = new DefaultFtpSessionFactory();
        toReturn.setHost(ftpSettings.getHost());
        toReturn.setPort(ftpSettings.getPort());
        toReturn.setUsername(ftpSettings.getUser());
        toReturn.setBufferSize(ftpSettings.getBufferSize());
        return toReturn;
    }
    
    @Bean
    public FtpStreamingMessageSource streamingFtpAdapter() {
        RemoteFileTemplate<FTPFile> template = new RemoteFileTemplate<>(ftpSessionFactory());
        template.setFileNameExpression(new LiteralExpression(ftpSettings.getFilePattern()));
        
        FtpStreamingMessageSource toReturn = new FtpStreamingMessageSource(template);
        toReturn.setRemoteDirectoryExpression(new LiteralExpression(ftpSettings.getRemoteDir()));
        toReturn.setRemoteFileSeparator("/");
        return toReturn;
    }

    @Bean
    public IntegrationFlow streamingftpFlow(){
        
        return IntegrationFlows.from(streamingFtpAdapter(), e -> e.poller(ftpPoller()))
                 .transform(streamToBytesTransformer())
                 // Further business logic
                 .get();
     }

    @Bean
    public StreamTransformer streamToBytesTransformer(){
        return new StreamTransformer();
    }
```

As you can see, this is much more cumbersome than the usual `Ftp.inboundAdapter(ftpSessionFactory())` plus the fluent API that allows the user to inline further settings.

Also, along with the new utility method, could be possible to have a new static method in `Transformers` that would provide a Stream to byte[] transformation? In that case, it would spare me creating the empty `streamToBytesTransformer` bean.

Thanks a lot!
Victor

**Comment by artembilan** [comment]
Since this project is intensively moving to the Spring Integration 5.0: https://github.com/spring-projects/spring-integration/wiki/Spring-Integration-4.3-to-5.0-Migration-Guide#java-dsl, we don't provide any new feature here any more. The `Ftp` factory there in the `spring-integration-ftp` module already has desired `inboundStreamingAdapter()`. Here is a test-case on the matter: https://github.com/spring-projects/spring-integration/blob/master/spring-integration-ftp/src/test/java/org/springframework/integration/ftp/dsl/FtpTests.java#L138.

As for the `StreamTransformer`. The `Transformers` there is indeed already enhanced with that as well:
```
	/**
	 * The factory method for the {@link StreamTransformer}.
	 * @return the {@link StreamTransformer} instance.
	 */
	public static StreamTransformer fromStream() {
		return fromStream(null);
	}

	/**
	 * Create an instance with the charset to convert the stream to a
	 * String; if null a {@code byte[]} will be produced instead.
	 * @param charset the charset.
	 * @return the {@link StreamTransformer} instance.
	 */
	public static StreamTransformer fromStream(String charset) {
		return new StreamTransformer(charset);
	}
```

On the other hand you don't need to create a `@Bean` for that even right now. This is fully enough:
```
 .transform(new StreamTransformer())
```
and Framework will take care about bean populated for you.

Right, for the `FtpStreamingMessageSource` we don't have choice unless use a workaround similar to yours.

I'm considering this issue as "Won't Fix" since we have it in the upcoming major version and you still have some good workaround.

Thank you for your feedback anyway!

**Comment by victor-ferrer** [comment]
OK, thanks @artembilan for the pointers! Really looking forward to the new Spring Integration 5!
Cheers,
Victor
