### ISSUE TITLE
Cannot @autowire MessagingGateway in @RestController

### ISSUE THREAD

**Issue by paskos** [spring-projects/spring-integration-java-dsl#21]
I have a `MessagingGateway` interface
```java
@MessagingGateway
public interface AppTypeUpgradeService
{
    @Gateway( requestChannel = "appTypeUpgrade.input" )
    void requestUpgrade( UserAndAppType userAndAppType );
}
```
it's injected in a `RestController`
```java
@RestController
@RequestMapping( APP_TYPE_REST_PATH )
public class AppTypeResource extends ApplicationObjectSupport
{
    @Autowired
    private AppTypeUpgradeService service;

    @RequestMapping( method = PUT, consumes = APPLICATION_JSON_VALUE )
    public void requestUpgrade()
    {
        service.requestUpgrade( provider.getUserAndAppType() );
    }
}
```
My `IntegrationFlow` is declared in a separate `Configuration`
```java
@Bean
public IntegrationFlow appTypeUpgrade()
{
    return f -> f.transform( transformer ).handle( handler );
}
```

In this configuration I keep getting `No bean named "appTypeUpgrade.input" is defined` error because my rest controller is initialized by spring before the flow configuration class.

I found a workaround in the RestController
```java
@RequestMapping( method = PUT, consumes = APPLICATION_JSON_VALUE )
public void requestUpgrade()
{
     AppTypeUpgradeService service = super.getApplicationContext().getBean( AppTypeUpgradeService.class );
     service.requestUpgrade( provider.getUserAndAppType() );
}
```
Is there a way to use `@Autowired`I couldn't find ?

Thanks

Paskos

**Comment by artembilan** [comment]
Well, looks like `AutowiredAnnotationBeanPostProcessor` works before `IntegrationFlowBeanPostProcessor`. Hence the `GatewayProxyFactoryBean` for your `AppTypeUpgradeService` doesn't see that `auto-created` channel for the `appTypeUpgrade.input` name.
Since Spring isn't designed for such a late-created beans, we don't have a choice unless declare that bean patently:
````java
@Bean(name = "appTypeUpgrade.input")
public MessageChannel appTypeUpgradeInput() {
     return new DirectChannel();
}
````

Anyway thank you for pointing that out. I think we'll find some ways to cover some of similar cases to allow avoid such explicit `DirectChannel` bean definitions.

**Comment by paskos** [comment]
Thanks for the work around.
Maybe you could lobby for ordered `BeanPostProcessor` then `IntegrationFlowPostProcessor`would execute before.
Or `IntegrationFlowPostProcessor` could implement `BeanDefinitionRegistryPostProcessor`, I think it it triggered before `BeanPostProcessor`.
If I find some time I'll give it a go and go back to you.

**Comment by artembilan** [comment]
@paskos , unfortunately the `BPP`s reorder (or other your trick) won't help. This `channel lazy-creation` works only if we don't have any initialization phase dependencies, e.g. this `@Autowired` case. And we can't move `IntegrationFlowPostProcessor` before `AutowiredAnnotationBeanPostProcessor`, because we will lose a lot of internal Spring Container stuff.
Only the best way to make it worked: adding `late-binding` logic to the `GatewayProxyFactoryBean`.
I'm not sure how we have missed that when we have added `late-binding` to the `MessagingGatewaySupport`.

So, it's not an issue of DSL, but core Spring Integration: https://jira.spring.io/browse/INT-3668.
Closing this one in favor of that and with the fact that we have a workaround.
