### ISSUE TITLE
Move docs towards users without SI XML experience

### ISSUE THREAD

**Issue by jramsdale** [spring-projects/spring-integration-java-dsl#32]
I'm aware of the concepts behind Spring Integration and I'm comfortable with them. I'm also a Spring user very comfortable with Java Config and Spring Boot. I don't, however, have experience with Spring Integration's XML configuration. I find it quite difficult to read Spring Integration's documentation and (to a lesser extent) the DSL's docs here because of the XML indirection. I imagine over time there will be more and more users like me--those approaching SI via the DSL only. I'd like to offer my plea here to cater more to me and a like audience. There's some great work in here, but it's nearly unapproachable sometimes, and it deserves to be seen.

**Comment by garyrussell** [comment]
Yes, we recognize that more and more people are using Java Configuration; we started adding more comprehensive annotation support in 4.0, by allowing EIP annotations on `@Bean`s and went further in 4.1 providing support for the DSL. The DSL still has gaps, and we are using community feedback to flesh it out. When it is more complete, it (and its documentation) will be folded into the core project.

We do have a plan to add more and more java config/DSL documentation and samples. But this will take some time, due to the sheer volume; the reference manual is already in excess of 450 pages and the effort to supplement all the configuration examples is quite large.

As with the DSL, ongoing work to improve the documentation is, by necessity, prioritized by user requests; we recently added [documentation](http://docs.spring.io/spring-integration/docs/4.2.0.BUILD-SNAPSHOT/reference/html/ip.html#ip-annotation) and [enhanced the sample](https://github.com/spring-projects/spring-integration-samples/commit/b5e7cfa16ac14bc0e0ab5f74f2bd8108b011d04b) directly as a result of a user request about how to configure a TCP outbound gateway using Java Configuration.

So, please feel free to request some specific requirements "how do I do X, Y" etc and we will do our best to respond with documentation changes as time permits, while giving you a short-term answer to your specific questions, either here or on Stack Overflow (with the `spring-integration` tag).

Thanks for the feedback!

**Comment by artembilan** [comment]
Thank you both as for feedback as well for answer!
Many DSL cases and configuration variants are covered with our tests: 
https://github.com/spring-projects/spring-integration-java-dsl/tree/master/src/test/java/org/springframework/integration/dsl/test
So, you can choose a required protocol specific package (`amqp`, `kafka`, `sftp` etc.) and take a look how you can configure appropriate adapter. E.g. JMS Message Driven Channel Adapter: https://github.com/spring-projects/spring-integration-java-dsl/blob/master/src/test/java/org/springframework/integration/dsl/test/jms/JmsTests.java#L223

**Comment by artembilan** [comment]
Starting with Spring Integration 4.2 we are adding more and more Java DSL samples to the Spring Integration Reference Manual, for example the `File Reading Component`: http://docs.spring.io/spring-integration/reference/html/files.html#_configuring_with_the_java_dsl_6.

We are going to move Java DSL into the Core project since version 5.0.

So, I'm considering this issue as fixed, because the work is being done on the matter.

Thank for the feedback anyway!

**Comment by jramsdale** [comment]
Much appreciated!
