### ISSUE TITLE
Log warning if an IntegrationFlow bean is present but @EnableIntegration annotation is missing

### ISSUE THREAD

**Issue by marinoj** [spring-projects/spring-integration-java-dsl#58]
Wouldn't it be a good idea to log a warning if there are IntegrationFlow beans present in the config but not an @EnableIntegration annotation?  Silently _not_ receiving messages can be pretty easy to miss.

**Comment by artembilan** [comment]
This is a stick with two ends. 
We can determine `IntegrationFlow`s only from the Spring Integration infrastructure, which is done by the `@EnableIntegration`.
The same problem we have with any other`@Enable...`. If you forget to add it, you won't have those specific beans and behavior.

The simple sample is: if you don't add `@EnableAsync`, your `@Async` method won't be `async`.

Your thoughts ?

**Comment by marinoj** [comment]
Fair enough - there are no IntegrationFlow beans as far as java-dsl is concerned if there is no @EnableIntegration annotation in the first place.  Not much to do about that I guess :)

Thanks for the fast response!  I really appreciate what you guys are doing.

**Comment by artembilan** [comment]
No problem!

That was a good question anyway!

Have never concerned how to be since the answer was always like: to make it working don't forget to add `@Enable...`!
That's why we have Spring Boot, where we can  not care about all off them because of `auto-config`.
But, yes, we still should not forget to add `@SpringBootApplication` :wink:
