### ISSUE TITLE
Lambda .input Channel Sometimes Not Declared

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-integration-java-dsl#61]
See https://github.com/spring-projects/spring-integration-samples/pull/162

I had to declare the channel as a bean.

**Comment by garyrussell** [comment]
Problem is in the `@InboundChannelAdapter` BPP - the `.input` is not yet available.

	@Configuration
	public static class Adapter {

		@Bean
		@InboundChannelAdapter(value = "mqttOutFlow.input", poller = @Poller(fixedDelay="1000") )
		public CharacterStreamReadingMessageSource source() {
			return CharacterStreamReadingMessageSource.stdin();
		}

	}

is a work around.

**Comment by garyrussell** [comment]
I guess we can't mix `@IBCA` with DSL.

Not sure it's worth addressing.

**Comment by artembilan** [comment]
Well, I'm sure we can address it from the SI Code perspective: Channel Auto-Creation hook for the `SourcePollingChannelAdapter`. The same what we have in the `AbstractMethodAnnotationPostProcessor.createEndpoint()` instead of just:
```
MessageChannel channel = this.channelResolver.resolveDestination(channelName);
```
like it is right now in the `InboundChannelAdapterAnnotationPostProcessor`.

WDYT ?

**Comment by garyrussell** [comment]
Yes; agreed; we can close this and open a JIRA over there.

**Comment by artembilan** [comment]
No. 
We can keep this to track the changes from there in face of test-case on the matter.

**Comment by artembilan** [comment]
The linked JIRA ticket: https://jira.spring.io/browse/INT-3961
