### ISSUE TITLE
JPA adapter DSL

### ISSUE THREAD

**Issue by englishman** [spring-projects/spring-integration-java-dsl#67]
I've reviewed some already implemented adapters (sftp, ftp etc.) and I have some questions:

1. All adapters have some central part like JMS.java or Ftp.java​ with some static factory methods. So
1.1 Why such classes are `abstract`? Is someone gonna to extend them somehow?
1.2 What is strategy for adding factory methods? Do you have some guide for this or conventions?

2. What is the purpose of e.g. `SftpMessageHandlerSpec`, `MailSendingMessageHandlerSpec` or any `*MessageHandlerSpec` classes?

3. Is this functionality should be placed at org.springframework.integration.dsl.*jpa*?

**Comment by artembilan** [comment]
Relates to https://jira.spring.io/browse/INTEXT-205

**Comment by artembilan** [comment]
(1.1) No-op. Just was a choice for the utility class with only `static` method. Like `org.springframework.util.StringUtils`. We started recently to migrate some other our project to *only* the style with the [CheckStyle](http://checkstyle.sourceforge.net/) rules. So, right, eventually we should migrate this projects as well. And finally all those `abstract` factory classes will be `final` with `private` ctor.

(1.2) In the particular protocol-specific part we should make those factory methods according to the existing adapters in the target Spring Integration module. See `Amqp` and `Jms` for example. So, this particular `Jpa` should have static methods as `inboundAdapter()`, `outboundAdapter`, `outboundGateway`. See the [Using Protocol Adapters](https://github.com/spring-projects/spring-integration-java-dsl/wiki/Spring-Integration-Java-DSL-Reference#adapters) on the matter, too.

(2) They are just builders around the target components. E.g. `SftpMessageHandlerSpec` is for the `FileTransferringMessageHandler<ChannelSftp.LsEntry>` and so on.

(3) Yeah. no choice. Since it is JPA, it should be in the `.jpa` package. That would be much easier to move it into the Spring Integration Core project, when time comes.

Hope I'm clear.

**Comment by englishman** [comment]
Also see answer 
http://stackoverflow.com/questions/36205972/jpa-outbound-channel-adapter-config-in-spring-integration-java-dsl
