### ISSUE TITLE
wireTap DSL usage improvement

### ISSUE THREAD

**Issue by englishman** [spring-projects/spring-integration-java-dsl#69]
Add logging ability as specific type of `MessageChannelSpec` interceptor. The purpose is a quick ability to log all messages go through specific channel. E.g. 

```java
@Bean
    public QueueChannel inputChannel() {
        return MessageChannels.queue(500)
            .log(...)
            .get();
    }
```
See discussion
http://stackoverflow.com/questions/35663452/wiretap-configuration-in-spring-integration-java-dsl

**Comment by artembilan** [comment]
@englishman ,

please, provide more info for the concern.

You know, sometimes we even don't need to fix anything and the issue is finishing just after discussion and explanation :smile: 

Anyway I'm glad to see any feedback!

**Comment by englishman** [comment]
@artembilan added description to the initial post

**Comment by artembilan** [comment]
Well, from one side we have similar behavior already (see #70):
````java
.channel(myChannel())
.log(LoggingHandler.Level.DEBUG)
````
From other side it won't be possible from that definition because we need to populate several beans into the application context, but `MessageChannelSpec` doesn't have the access to it and won't have. It even isn't allowed to be as a bean. Therefore any internals for such a `.log()` trick on the `MessageChannelSpec` should be populated somehow externally. 

I'm not sure yet that we will be possible to overcome somehow the gap between Builder phase and Bean Definition one, but right now I see only this working solution for you:
````
@Bean
public PollableChannel splittingChannel() {
	return MessageChannels.queue(500)
			.interceptor(new WireTap(loggingChannel()))
			.get();
}

@Bean
public MessageChannel loggingChannel() {
	return new DirectChannel();
}

@Bean
public IntegrationFlow loggingFlow() {
	return IntegrationFlows.from(loggingChannel())
			.log()
			.get();
}
````
I think this should be enough close to XML variant by the code line count :smile: 

So, we may come to the desired solution somewhere in the future, when we find something for the `Spec` population in the application context.
Or we will just live with the existing solution and the provided workaround.

Although I guess we can add `.wireTap()` method to the `MessageChannelSpec` and even make `WireTap` as *Late Binding* to allow to inject `channelName`, not a whole `MessageChannel` instance.
With that we will be able to have the config like:
````java
@Bean
public PollableChannel splittingChannel() {
	return MessageChannels.queue(500)
			.wireTap("loggingFlow.input")
			.get();
}

@Bean
public IntegrationFlow loggingFlow() {
	return f -> f.log();
}
````

@englishman , let me know WDYT and we go ahead with some fix.

Thank you again for the feedback!

**Comment by artembilan** [comment]
See also: https://jira.spring.io/browse/INT-3998

**Comment by artembilan** [comment]
Please, find the #76 PullRequest on the matter.
According the latest SI Core changes for the `WireTap` we were be able to provide further simplification for the `.wireTap()` declaration.
Also now `MessageChannelSpec` has `.wireTap()` additions.
Note: for this purpose we have to leave `IntegrationComponentSpec` as a `@Bean` to allow the Framework parse and populate beans properly.
So, the previous sample for `log` should be like this now:
````java
@Bean
public QueueChannelSpec splittingChannel() {
    return MessageChannels.queue()
            .wireTap("loggingFlow.input");
}

@Bean
public IntegrationFlow loggingFlow() {
    return f -> f.log();
}
````
