### ISSUE TITLE
Use parametrized GenericSelector<S> in RecipientListRouterSpec

### ISSUE THREAD

**Issue by englishman** [spring-projects/spring-integration-java-dsl#74]
Currently in class `RecipientListRouterSpec` it's possible to use either `MessageSelector` or `String` expression instance in `recipientFlow` method. The both options are not type safe.

It would be logical to allow using `GenericSelector<S>` in `recipientFlow` instance too. The close analog is an ability to use `GenericTransformer<S, T>` in `IntegrationFlowDefinition#transform` method.

**Comment by artembilan** [comment]
Hello, @englishman !

Would you mind to comment similar way on all other your issues?

For this one case we don't have choice with the `GenericSelector` because the `RecipientListRouter.Recipient` can accept only `MessageSelector`.
I think we will be able to overcome the requirements with the `Function<Message<P>, Boolean>` and `FunctionExpression`  underneath.

Thank you for the report!
