### ISSUE TITLE
No way to define 'default-output-channel' in router spec

### ISSUE THREAD

**Issue by englishman** [spring-projects/spring-integration-java-dsl#77]
Currently `org.springframework.integration.dsl.RouterSpec` has ability to set `resolution-required` attribute but doesn't have ability to set `default-output-channel`.

This attribute is crucial if I want don't silently drop messages in `else` branch but do smth specific action with them (e.g. logging).

**Comment by artembilan** [comment]
The `default-output-channel` of the `Router` component is just like an `outputChannel` property of the `AbstractMessageProducingHandler`. So, according to that assumption the next `.channel()` after the `.route()` is exactly that `otherwise` branch, provide by the `default-output-channel` option:
````java
@Bean
public IntegrationFlow routeSubflowWithoutReplyToMainFlow() {
	return f -> f
			.<String, Boolean>route("BOO"::equals, m -> m
					.resolutionRequired(false)
					.subFlowMapping("true", sf -> sf
							.transform(String.class, String::toLowerCase)
							.channel(c -> c.queue("routerSubflowResult"))))
			// Valid: maps to the router's defaultOutputChannel
			.channel("defaultOutputChannel");
}
````
Does it make sense for you?

**Comment by artembilan** [comment]
See an external discussion: http://stackoverflow.com/questions/36812276/eip-router-usage-without-introducing-a-new-channel-after

**Comment by englishman** [comment]
@artembilan actually, I've already used `.channel(...)` statement like you've proposed. Here is my almost real code:
```java
    @Bean
    public IntegrationFlow realMessageFlow(
            RealConfirmationCreator realConfirmationCreator
    ) {
        return IntegrationFlows.from(impactInputChannel())
                .enrichHeaders(s -> s
                        .<RealSettlementMessage>headerFunction(CHANGE_ACTION_FLAG, f -> f.
                                getPayload().getChangeFlag())
                )
                .transform(realConfirmationCreator)
                .route("headers['" + CHANGE_ACTION_FLAG + "']", r -> r
                        .subFlowMapping("S", f -> f
                                .enrich(p -> p.property("messageType", "REAL_VALUE_1"))
                                .channel(CHANGE_ACTION_CHANNEL)
                        )
                        .subFlowMapping("V", f -> f
                                .enrich(p -> p.property("messageType", "REAL_VALUE_2"))
                                .channel(CHANGE_ACTION_CHANNEL)
                        )
                )
                .channel("nullChannel")
                .get();
    }
```
As you can see my enriching logic in `router` is very simple and later I have the same flow for the both branches of execution (for "S" and "V" value) so it's good idea to use approach you proposed me earlier: remove `CHANGE_ACTION_CHANNEL` and put following pipeline steps just after `router`. But I can't don this as I use `.channel("nullChannel")` like [EIP InvalidMessageChannel](http://www.enterpriseintegrationpatterns.com/patterns/messaging/InvalidMessageChannel.html). 

So it would be ideal for me to have smth like `.defaultSubFlow(...)` statement here in the scope of `router`

Another thing: I have expression `"headers['" + CHANGE_ACTION_FLAG + "']"` as the `router` selector. It's a `String` and has 2 valid values but potentially may have infinite value set (in another part of my flow I have 4 valid values). How can I rewrite the expression to introduce a technical `"default"` value?

**Comment by artembilan** [comment]
Hello, @englishman !

Thank you for comprehensive feedback!

Well, let me answer to your concerns one by one:

1. `EIP InvalidMessageChannel` is exactly for the `errorChannel`. The `nullChannel` plays role like [/dev/null](http://docs.spring.io/spring-integration/reference/html/messaging-channels-section.html#channel-special-channels). But yes, you can treat it like `Invalid` in your application! :smile: 

2. Thinking about what we have with that `.channel()` after `.route()` as an `otherwise` branch and the `bridging` from the subflow to the same "after-route-channel", I find your concern enough valid and have changed my mind.
We definitely should introduce something like `RouterSpec.default(Channel/IntegrationFlow)` and let that "after-route-channel" work only as a bridge from subflows. If all the router's mapping is based on the channels, you can go to that "after-route-channel" only via explicit reference from the downstream flow of the mapping.

3. `How can I rewrite the expression to introduce a technical "default" value?`
No-op. See previous item.

4. `nullChannel` constant - `IntegrationContextUtils.NULL_CHANNEL_BEAN_NAME`. And there you can find more useful bean names.

**Comment by englishman** [comment]
@artembilan 

1. I was in the middle or rethinking this so... some misconception was happened :)
2. Let me try to implement this as PR if you don't have any objects.
4. Thanks! But... don't like this `_BEAN_NAME` postfix :( I want to see clean name like `NULL_CHANNEL` in my flow definition.

**Comment by artembilan** [comment]
Thank you for coming back, @englishman !

> I was in the middle or rethinking this so... some misconception was happened 

That's fine. As you see even here with router the initial decision became not so good.

> Let me try to implement this as PR if you don't have any objects.

:+1: That's what I'm looking for from the community! Some real DSL usage and good feedback in face of PRs. BTW review for existing PRs would be good too :wink. And, of course, you feel free to implement any other issues. Seems for me we agreed there what and how to do. 

>  But... don't like this _BEAN_NAME postfix :( I want to see clean name like NULL_CHANNEL in my flow definition.

Yeah... Agreed. I don't like them as well. I can recall that's why we have introduced `PollerMetadata.DEFAULT_POLLER`. Exactly for similar JavaConfig cases to make it more convenient.
All those `IntegrationContextUtils` were created in that era when Spring Integration had only XML configuration variant. 

So, feel free to raise a [JIRA](https://jira.spring.io/browse/INT) against Core project to introduce those convenient constants.
